source 'https://github.com/CocoaPods/Specs.git'

platformVersion = '12.0'
platform :ios, platformVersion

inhibit_all_warnings!

target 'MixParadise' do
    pod 'MRGTaylor'
    pod 'PinLayout'
    pod 'ActionKit'
    pod 'Kingfisher'
    pod 'Cheers'
    pod 'SwiftHEXColors'
    pod 'Alamofire'
    pod 'AlamofireImage'
end
